/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Landing Page Teal Palette
        brand: {
          50: '#f0fdfa',
          100: '#ccfbf1',
          200: '#99f6e4',
          300: '#5eead4',
          400: '#2dd4bf',
          500: '#14b8a6',
          600: '#0d9488',
          700: '#0f766e',
          800: '#115e59',
          900: '#134e4a',
        },
        // Enterprise Operational Palette (from Reference UI HTMLs)
        "primary": "#00236f",
        "primary-container": "#1e3a8a",
        "primary-fixed": "#dce1ff",
        "primary-fixed-dim": "#b6c4ff",
        "inverse-primary": "#b6c4ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#90a8ff",
        "on-primary-fixed": "#00164e",
        "on-primary-fixed-variant": "#264191",

        "secondary": "#0051d5",
        "secondary-container": "#316bf3",
        "secondary-fixed": "#dbe1ff",
        "secondary-fixed-dim": "#b4c5ff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#fefcff",
        "on-secondary-fixed": "#00174b",
        "on-secondary-fixed-variant": "#003ea8",

        "tertiary": "#003120",
        "tertiary-container": "#004a32",
        "tertiary-fixed": "#85f8c4",
        "tertiary-fixed-dim": "#68dba9",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#4ac08f",
        "on-tertiary-fixed": "#002114",
        "on-tertiary-fixed-variant": "#005137",

        "surface": "#faf8ff",
        "surface-bright": "#faf8ff",
        "surface-dim": "#d2d9f4",
        "surface-tint": "#4059aa",
        "surface-variant": "#dae2fd",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",

        "on-surface": "#131b2e",
        "on-surface-variant": "#444651",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",

        "outline": "#757682",
        "outline-variant": "#c5c5d3",

        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",

        "background": "#faf8ff",
        "on-background": "#131b2e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        "margin-desktop": "2rem",
        "gutter-desktop": "1.5rem",
        "gutter": "1rem",
        "margin": "1rem",
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'Geist', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'Geist', 'monospace'],
        "label-sm": ['Geist', 'sans-serif'],
        "body-md": ['Geist', 'sans-serif'],
        "headline-lg": ['"Hanken Grotesk"', 'sans-serif'],
        "tabular-metric-md": ['Geist', 'monospace', 'sans-serif'],
        "label-md": ['Geist', 'sans-serif'],
        "body-sm": ['Geist', 'sans-serif'],
        "code-sm": ['Geist', 'monospace'],
        "headline-sm": ['"Hanken Grotesk"', 'sans-serif'],
        "tabular-metric-lg": ['Geist', 'monospace', 'sans-serif'],
        "headline-xl": ['"Hanken Grotesk"', 'sans-serif'],
        "body-lg": ['Geist', 'sans-serif'],
      },
      fontSize: {
        "label-sm": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.03em", fontWeight: "500" }],
        "body-md": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "headline-lg": ["1.375rem", { lineHeight: "1.75rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "tabular-metric-md": ["1.125rem", { lineHeight: "1.375rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.125rem", fontWeight: "400" }],
        "code-sm": ["0.75rem", { lineHeight: "1rem", fontWeight: "400" }],
        "headline-sm": ["1.125rem", { lineHeight: "1.5rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "tabular-metric-lg": ["1.5rem", { lineHeight: "1.75rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["0.9375rem", { lineHeight: "1.375rem", fontWeight: "400" }],
      }
    },
  },
  plugins: [],
}
